-- Awas Abu Phase 0
-- Run in the Supabase SQL editor with a project-owner account.

create table if not exists public.aa_area (
  code       text primary key,
  name       text not null,
  regency    text not null,
  province   text not null,
  lat        double precision not null check (lat between -90 and 90),
  lng        double precision not null check (lng between -180 and 180),
  aliases    text[] not null default '{}',
  created_at timestamptz not null default now()
);

create index if not exists aa_area_aliases_idx
  on public.aa_area using gin (aliases);

do $$ begin
  create type public.aa_level as enum ('AMAN', 'WASPADA', 'AWAS_ABU', 'BAHAYA');
exception when duplicate_object then null;
end $$;

create table if not exists public.aa_status (
  id          bigint generated by default as identity primary key,
  area_code   text not null references public.aa_area(code) on delete cascade,
  level       public.aa_level not null,
  headline    text not null check (char_length(headline) between 1 and 500),
  actions     text[] not null default '{}',
  source_name text not null check (char_length(source_name) between 1 and 100),
  source_url  text not null check (source_url ~ '^https://'),
  observed_at timestamptz not null,
  expires_at  timestamptz not null check (expires_at > observed_at),
  operator    text not null check (char_length(operator) between 1 and 100),
  created_at  timestamptz not null default now()
);

create index if not exists aa_status_area_idx
  on public.aa_status (area_code, created_at desc);

create or replace view public.aa_status_current
with (security_invoker = true) as
select distinct on (area_code) *
from public.aa_status
order by area_code, created_at desc;

create table if not exists public.aa_subscriber (
  phone      text primary key check (phone ~ '^[0-9]{8,16}$'),
  area_code  text references public.aa_area(code) on delete set null,
  active     boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Keep explicit opt-in safe even when upgrading from the loose Phase 0 draft.
alter table public.aa_subscriber alter column active set default false;

create table if not exists public.aa_inbound (
  id         bigint generated by default as identity primary key,
  phone      text not null check (phone ~ '^[0-9]{8,16}$'),
  intent     text not null check (
    intent in ('location', 'area', 'daftar', 'stop', 'help', 'unknown')
  ),
  area_code  text references public.aa_area(code) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists aa_inbound_phone_idx
  on public.aa_inbound (phone, created_at desc);

create or replace function public.aa_is_rate_limited(p_phone text)
returns boolean
language sql
stable
set search_path = ''
as $$
  select count(*) >= 6
  from public.aa_inbound
  where phone = p_phone
    and created_at > now() - interval '5 minutes';
$$;

create or replace function public.aa_prune_inbound()
returns void
language sql
set search_path = ''
as $$
  delete from public.aa_inbound
  where created_at < now() - interval '7 days';
$$;

-- Server-only access. The service-role key bypasses RLS; never ship it to a client.
alter table public.aa_area enable row level security;
alter table public.aa_status enable row level security;
alter table public.aa_subscriber enable row level security;
alter table public.aa_inbound enable row level security;

revoke all on table public.aa_area from anon, authenticated;
revoke all on table public.aa_status from anon, authenticated;
revoke all on table public.aa_subscriber from anon, authenticated;
revoke all on table public.aa_inbound from anon, authenticated;
revoke all on table public.aa_status_current from anon, authenticated;
revoke execute on function public.aa_is_rate_limited(text) from public, anon, authenticated;
revoke execute on function public.aa_prune_inbound() from public, anon, authenticated;
grant execute on function public.aa_is_rate_limited(text) to service_role;
grant execute on function public.aa_prune_inbound() to service_role;

insert into public.aa_area
  (code, name, regency, province, lat, lng, aliases)
values
  ('BTN-SRG-CNK','Cinangka','Kab. Serang','Banten',-6.2833,105.8333,'{cinangka,pasauran,karangbolong}'),
  ('BTN-SRG-ANY','Anyar','Kab. Serang','Banten',-6.0833,105.9000,'{anyar,anyer}'),
  ('BTN-SRG-BJN','Bojonegara','Kab. Serang','Banten',-5.9333,106.0833,'{bojonegara}'),
  ('BTN-SRG-PAM','Pulo Ampel','Kab. Serang','Banten',-5.9000,106.0500,'{pulo ampel,puloampel}'),
  ('BTN-PDG-CRT','Carita','Kab. Pandeglang','Banten',-6.3167,105.8333,'{carita}'),
  ('BTN-PDG-LBN','Labuan','Kab. Pandeglang','Banten',-6.3833,105.8333,'{labuan}'),
  ('BTN-PDG-PNB','Panimbang','Kab. Pandeglang','Banten',-6.4667,105.6667,'{panimbang,tanjung lesung}'),
  ('BTN-PDG-SMR','Sumur','Kab. Pandeglang','Banten',-6.6500,105.5000,'{sumur,ujung kulon}'),
  ('BTN-PDG-CGL','Cigeulis','Kab. Pandeglang','Banten',-6.5500,105.6167,'{cigeulis}'),
  ('BTN-PDG-SKR','Sukaresmi','Kab. Pandeglang','Banten',-6.4000,105.8500,'{sukaresmi}'),
  ('BTN-CLG-KOT','Kota Cilegon','Kota Cilegon','Banten',-6.0167,106.0167,'{cilegon,merak}'),
  ('BTN-SRG-KOT','Kota Serang','Kota Serang','Banten',-6.1200,106.1500,'{kota serang,serang}'),
  ('LPG-LSL-KLD','Kalianda','Kab. Lampung Selatan','Lampung',-5.7500,105.5833,'{kalianda}'),
  ('LPG-LSL-RJB','Rajabasa','Kab. Lampung Selatan','Lampung',-5.8000,105.6500,'{rajabasa,canti,kunjir}'),
  ('LPG-LSL-BKH','Bakauheni','Kab. Lampung Selatan','Lampung',-5.8667,105.7500,'{bakauheni}'),
  ('LPG-LSL-PNH','Penengahan','Kab. Lampung Selatan','Lampung',-5.7333,105.6667,'{penengahan}'),
  ('LPG-LSL-KTB','Katibung','Kab. Lampung Selatan','Lampung',-5.5667,105.4333,'{katibung}'),
  ('LPG-LSL-SDM','Sidomulyo','Kab. Lampung Selatan','Lampung',-5.6167,105.5500,'{sidomulyo}'),
  ('LPG-BDL-PJG','Panjang','Kota Bandar Lampung','Lampung',-5.4667,105.3167,'{panjang}'),
  ('LPG-BDL-KOT','Bandar Lampung','Kota Bandar Lampung','Lampung',-5.4292,105.2610,'{bandar lampung,tanjung karang,teluk betung}'),
  ('JKT-KOT-DKI','DKI Jakarta','DKI Jakarta','DKI Jakarta',-6.2000,106.8167,'{jakarta,jakarta pusat,jakarta selatan,jakarta barat,jakarta timur,jakarta utara,jabodetabek}'),
  ('BTN-TNG-KOT','Kota Tangerang','Kota Tangerang','Banten',-6.1783,106.6319,'{tangerang,cengkareng,soekarno hatta}'),
  ('JBR-BDG-KOT','Kota Bandung','Kota Bandung','Jawa Barat',-6.9175,107.6191,'{bandung}')
on conflict (code) do nothing;

-- Schedule this daily after enabling pg_cron in Supabase:
-- select cron.schedule('awasabu-prune-inbound', '17 18 * * *',
--   $$select public.aa_prune_inbound();$$);
